version: "3.9"
services:
  # FastAPI
  web:
    container_name: web
    build: .
    volumes:
      - ./app/:/code/app
    ports:
      - "80:8000"
    depends_on:
      - postgres
  # PostgreSQL
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "leads"
      POSTGRES_USER: "roman"
      POSTGRES_PASSWORD: "superpwd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"